DELETE FROM Review WHERE stamp IS NOT NULL;

DELETE FROM Menu_item WHERE name IS NOT NULL;
DELETE FROM Menu WHERE name IS NOT NULL;

DELETE FROM User_favorites WHERE userName IS NOT NULL;
DELETE FROM User WHERE userName IS NOT NULL;

DELETE FROM Restaurant_address WHERE num IS NOT NULL;
DELETE FROM Restaurant_type WHERE att IS NOT NULL;
DELETE FROM Restaurant_hours WHERE days IS NOT NULL;
DELETE FROM Restaurant WHERE name IS NOT NULL;
